# Generated by Django 4.2.3 on 2023-09-22 22:18

from django.db import migrations, models
import sportsscores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='Leagaaa', max_length=50)),
                ('sport', models.CharField(blank=True, choices=[('SOCCER', 'Soccer'), ('FOOTBALL', 'Football')], default='SOCCER', max_length=15)),
                ('json_data', models.JSONField(default=sportsscores.models.League.default_json)),
            ],
        ),
    ]
