# Generated by Django 4.0.10 on 2023-11-03 02:46

import django.contrib.postgres.fields
from django.db import migrations, models
import sportsscores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='Leagaaa', max_length=50)),
                ('sport', models.CharField(blank=True, choices=[('SOCCER', 'Soccer'), ('FOOTBALL', 'Football')], default='SOCCER', max_length=15)),
                ('json_data', models.JSONField(default=sportsscores.models.League.default_json)),
                ('game_details', models.JSONField(blank=True, default=sportsscores.models.League.default_json)),
                ('logo', models.ImageField(default='default_image.png', upload_to='logos_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sport', models.CharField(blank=True, choices=[('SOCCER', 'Soccer'), ('FOOTBALL', 'Football')], default='SOCCER', max_length=15)),
                ('api_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('logo', models.ImageField(default='default_image.png', upload_to='logos_folder/')),
            ],
        ),
    ]
