# Generated by Django 4.0.10 on 2023-11-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('api_source', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sport', models.CharField(choices=[('SOCCER', 'Soccer'), ('FOOTBALL', 'Football')], max_length=255)),
                ('raw_json', models.JSONField()),
                ('logo', models.ImageField(upload_to='logos_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('api_source', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos_folder/')),
                ('league', models.ManyToManyField(related_name='teams', to='sportsscores.league')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='sportsscores.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='sportsscores.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsscores.league')),
            ],
        ),
    ]
