# Generated by Django 4.2.3 on 2023-09-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsscores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sport', models.CharField(blank=True, choices=[('SOCCER', 'Soccer'), ('FOOTBALL', 'Football')], default='SOCCER', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsscores.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsscores.team')),
            ],
            options={
                'unique_together': {('team', 'league')},
            },
        ),
    ]
