# Generated by Django 4.0.10 on 2023-11-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsscores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='raw_json',
            new_name='json_data',
        ),
    ]
