# Generated by Django 4.0.10 on 2023-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsscores', '0002_rename_raw_json_league_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(related_name='league', to='sportsscores.team'),
        ),
    ]
