# Generated by Django 4.2.3 on 2023-09-26 03:24

from django.db import migrations, models
import sportsscores.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsscores', '0004_remove_team_api_id_teamleague_team_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleague',
            name='json_data',
            field=models.JSONField(default=sportsscores.models.TeamLeague.default_json),
        ),
    ]
