# Generated by Django 4.0.10 on 2023-10-04 01:25

from django.db import migrations, models
import sportsscores.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsscores', '0005_teamleague_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='game_details',
            field=models.JSONField(default=sportsscores.models.League.default_json),
        ),
    ]
